name: Build

on: [push, workflow_dispatch]

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      matrix:
        include:
          - { sys: mingw32, env: i686 }
          - { sys: mingw64, env: x86_64 }
    steps:
    - uses: actions/checkout@v2
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        update: true
        install: >-
          base-devel
          git
          mingw-w64-${{matrix.env}}-cmake
          mingw-w64-${{matrix.env}}-meson
          mingw-w64-${{matrix.env}}-toolchain
          mingw-w64-${{matrix.env}}-nasm
          mingw-w64-${{matrix.env}}-zimg
          mingw-w64-${{matrix.env}}-libiconv
          mingw-w64-${{matrix.env}}-libass
    - name: Install VapourSynth
      run: |
        git clone https://github.com/vapoursynth/vapoursynth.git --depth 1
        pushd vapoursynth
        ./autogen.sh
        ./configure --disable-vsscript --disable-vspipe --disable-python-module
        make install -j2
        popd
        rm -rf vapoursynth
    - name: Install FFmpeg
      run: |
        git clone https://github.com/FFmpeg/FFmpeg --branch release/4.4 --depth 1
        pushd FFmpeg
        ./configure --enable-pic --disable-doc --enable-debug --enable-runtime-cpudetect --enable-asm --enable-x86asm --disable-ffmpeg --disable-ffplay --disable-ffprobe --enable-avcodec --enable-avdevice --enable-avformat --enable-avfilter --disable-postproc --enable-swresample --enable-swscale --disable-libass --disable-avisynth --disable-bzlib --disable-libdav1d --disable-libfdk-aac --disable-libfontconfig --disable-libfreetype --disable-libfribidi --disable-iconv --disable-libilbc --disable-lzma --disable-libmp3lame --disable-libmodplug --disable-cuda --disable-nvenc --disable-nvdec  --disable-cuvid --disable-ffnvcodec --disable-opencl --disable-opengl --disable-libopenh264 --disable-libopenjpeg --disable-openssl --disable-libopus --disable-sdl2 --disable-libsnappy --disable-libsoxr --disable-libspeex --disable-libssh --disable-libtensorflow --disable-libtesseract --disable-libtheora --disable-libvorbis --disable-libvpx --disable-libwebp --disable-libx264 --disable-libx265 --disable-libxml2 --disable-zlib
        make -j2
        sudo make install -j2
        popd
        rm -rf FFmpeg
    - name: Build
      run: |
        meson build -Dstatic=true
        ninja -C build
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: subtext-meson-mingw-${{matrix.env}}
        path: build/libsubtext.dll
