name: Build

on: [push, workflow_dispatch]

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    strategy:
      matrix:
        include:
          - { sys: mingw32, env: i686 }
          - { sys: mingw64, env: x86_64 }
    steps:
    - uses: actions/checkout@v2
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        update: true
        install: >-
          base-devel
          git
          mingw-w64-${{matrix.env}}-cmake
          mingw-w64-${{matrix.env}}-meson
          mingw-w64-${{matrix.env}}-toolchain
          mingw-w64-${{matrix.env}}-zimg
          mingw-w64-${{matrix.env}}-ffmpeg
          mingw-w64-${{matrix.env}}-libiconv
          mingw-w64-${{matrix.env}}-libass
    - name: Install VapourSynth
      run: |
        git clone https://github.com/vapoursynth/vapoursynth.git --depth 1
        pushd vapoursynth
        ./autogen.sh
        ./configure --disable-vsscript --disable-vspipe --disable-python-module
        make install -j2
        popd
        rm -rf vapoursynth
    - name: Build
      run: |
        meson build -Dstatic=true
        ninja -C build
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: subtext-meson-mingw-${{matrix.env}}
        path: build/libsubtext.dll
